"use strict";
require('es6-promise');
require('isomorphic-fetch');
process.env.NODE_ENV = 'test';
require('source-map-support').install();
require('./writeToStore');
require('./readFromStore');
require('./roundtrip');
require('./diffAgainstStore');
require('./networkInterface');
require('./QueryManager');
require('./client');
require('./store');
require('./queryTransform');
require('./getFromAST');
require('./directives');
require('./queryMerging');
require('./batching');
require('./scheduler');
require('./mutationResults');
require('./optimistic');
require('./fetchMore');
require('./scopeQuery');
require('./errors');
//# sourceMappingURL=tests.js.map